<!-- Copyright (c) Kirk Rader 2026 -->

<template>
    <math display="block">
        <mrow>
            <munder>
                <mo>lim</mo>
                <mrow>
                    <mi>x</mi>
                    <mo>&rarr;</mo>
                    <mrow>
                        <mo>&pm;</mo>
                        <mn>&infin;</mn>
                    </mrow>
                </mrow>
            </munder>
            <mo>(</mo>
            <mfrac>
                <mn>1</mn>
                <mi>x</mi>
            </mfrac>
            <mo>)</mo>
            <mo>=</mo>
            <mrow>
                <mo>&pm;</mo>
                <mn>0</mn>
            </mrow>
        </mrow>
        <mpadded width="1em" lspace="0.5em">
            <mo>&equiv;</mo>
        </mpadded>
        <mrow>
            <munder>
                <mo>lim</mo>
                <mrow>
                    <mi>x</mi>
                    <mo>&rarr;</mo>
                    <mrow>
                        <mo>&pm;</mo>
                        <mn>0</mn>
                    </mrow>
                </mrow>
            </munder>
            <mo>(</mo>
            <mfrac>
                <mn>1</mn>
                <mi>x</mi>
            </mfrac>
            <mo>)</mo>
            <mo>=</mo>
            <mrow>
                <mo>&pm;</mo>
                <mn>&infin;</mn>
            </mrow>
        </mrow>
    </math>
</template>